apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-react-k-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr-react-k-app
  template:
    metadata:
      labels:
        app: ocr-react-k-app
    spec:
      volumes:
        - name: server-storage2
          persistentVolumeClaim:
            claimName: anas-pvc
      containers:
        - name: ocr-react-k-app
          image: anasalpure/ocr-react-app:1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "20Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app"
              name: server-storage2
