apiVersion: v1
kind: Service
metadata:
  name: ocr-react-k-service
spec:
  selector:
    app: ocr-react-k-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 80
  # externalIPs:
  #   - 172.17.0.1
